# Generated by Django 4.0.4 on 2022-04-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('bill_no', models.IntegerField(db_column='Bill_no', primary_key=True, serialize=False)),
                ('date_bill', models.CharField(blank=True, max_length=20, null=True)),
                ('tot_amt', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tripid', models.IntegerField(db_column='TripID')),
                ('payment_mode', models.CharField(blank=True, db_column='Payment_mode', max_length=10, null=True)),
                ('userid', models.IntegerField(blank=True, db_column='UserID', null=True)),
            ],
            options={
                'db_table': 'bill_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(blank=True, db_column='Car_ID', null=True)),
                ('registrationid', models.CharField(blank=True, db_column='RegistrationId', max_length=30, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=30, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('car_type', models.CharField(blank=True, db_column='Car_type', max_length=30, null=True)),
            ],
            options={
                'db_table': 'car_manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('employ_id', models.IntegerField(db_column='Employ_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('contact_no', models.CharField(blank=True, db_column='Contact_No', max_length=30, null=True)),
            ],
            options={
                'db_table': 'customer_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=30, null=True)),
                ('contact_no', models.CharField(blank=True, db_column='Contact_No', max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('driver_id', models.IntegerField(db_column='Driver_ID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, db_column='Feedback', max_length=30, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'premium_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('taxi_id', models.IntegerField(db_column='Taxi_id', primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('car_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taxi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripid', models.IntegerField(blank=True, db_column='TripID', null=True)),
                ('tripamount', models.FloatField(blank=True, db_column='TripAmount', null=True)),
                ('starttime', models.TextField(blank=True, db_column='StartTime', null=True)),
                ('endtime', models.TextField(blank=True, db_column='EndTime', null=True)),
                ('taxi_id', models.IntegerField(blank=True, db_column='Taxi_ID', null=True)),
                ('pool_num', models.IntegerField(blank=True, db_column='Pool_num', null=True)),
                ('startlocation', models.TextField(blank=True, db_column='StartLocation', null=True)),
                ('destination', models.TextField(blank=True, db_column='Destination', null=True)),
            ],
            options={
                'db_table': 'trip_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(db_column='UserID', primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, db_column='User_email', max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, db_column='Contact_No', max_length=30, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=30, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=30, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
